Feature/consolidate user service
revabam/bambam-client pull request #122
Opened 2018-10-01 20:39 UTC by jonwuzulike

Added functionality for a user to login solely with Cognito. The logged in user is identified by their token id.
Also added functionality to retrieve user attributes but unable to test this feature because of the hard-coded data in the Dashboard Component in this version of the dev branch.

![image](https://user-images.githubusercontent.com/29211719/46314408-7ac17600-c598-11e8-933f-4626b40caa42.png)

![image](https://user-images.githubusercontent.com/29211719/46314382-5fef0180-c598-11e8-9519-29998bb10e92.png)

![image](https://user-images.githubusercontent.com/29211719/46314343-42219c80-c598-11e8-99c9-db70c5df435b.png)

2018-10-01 20:56 UTC, jonwuzulike commented
![image](https://user-images.githubusercontent.com/29211719/46315224-e1e02a00-c59a-11e8-89d9-b1874c32b924.png)
I am able to get the attributes just unable to use them anywhere yet.

2018-10-02 05:07 UTC, MarcinSalamon requested changes

2018-10-02 05:07 UTC, MarcinSalamon commented on src/app/services/cognito.service.ts
> +    console.log('In Cognito getUserAttributes().........');
remove console logs, otherwise good

2018-10-02 14:35 UTC, humphreyminottjr submitted a review, later dismissed

2018-10-02 14:43 UTC, humphreyminottjr approved these changes

2018-10-02 14:45 UTC, merged