updated endpoints to match server-side.
revabam/bambam-client pull request #135
Opened 2018-10-02 20:25 UTC by ChineduOzodi

mapping the endpoints to server side. This breaks the ability to use the mock data client side since it takes more work to get custom endpoints created the mock data. I did replaced the mapping to server-side "/" to "-" to allow for compatibility and easy switching if the client side mock data is ever needed again.

2018-10-02 23:23 UTC, MarcinSalamon requested changes

2018-10-02 23:23 UTC, MarcinSalamon commented on src/app/routes/curriculum-editor/create-curriculum/create-curriculum.component.ts
> +          console.log('Resfreshing page');
delete, keep this commit short

2018-10-02 23:23 UTC, MarcinSalamon commented on src/app/routes/curriculum-editor/curriculum-editor.component.ts
> +      console.log('new curriculum');
delete

2018-10-02 23:23 UTC, MarcinSalamon commented on src/environments/environment.ts
> +  apiUrl: 'http://localhost:8765/bam/',
we already have zuul url

2018-10-03 05:09 UTC, ChineduOzodi reviewed
Looks good

2018-10-03 05:09 UTC, merged